export const quadrantState: [ number, number, boolean][][] = [
  [ [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false] ],
  [ [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false] ],
  [ [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false] ],
  [ [0, 0, false],
    [0, 0, false],
    [0, 7, false],
    [1, 6, false],
    [3, 4, true],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false] ],
  [ [0, 0, false],
    [0, 0, false],
    [0, 2, false],
    [0, 5, false],
    [0, 4, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false] ],
  [ [0, 0, false],
    [0, 0, false],
    [0, 1, false],
    [0, 5, false],
    [0, 6, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false] ],
  [ [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false] ],
  [ [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false],
    [0, 0, false] ] ];
